import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import ReactQueryClientProvider from "@/libs/query-component/query-component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <br></br>
          <h1>
            <Link href={"/"}>
              My Account Page
              <br></br>
            </Link>
          </h1>

          <Link href={"/profile"} style={{ padding: "20px" }}>
            Profile
          </Link>
          <Link href={"/orders"} style={{ padding: "20px" }}>
            Orders
          </Link>
          <Link href={"/settings"} style={{ padding: "20px" }}>
            Settings
          </Link>
          <br></br>
          <br></br>
        </div>
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
      </body>
    </html>
  );
}
